### ISSUE TITLE
Error when restoring wallet from backup file

### ISSUE THREAD

**Issue by john-light** [BobWallet/BobWallet#10]
When I try to restore the wallet from backup, I receive the following error in the wallet:

`JSON.parse: unexpected character at line 1 column 1 of the JSON data`

This is the file I am trying to restore:

`﻿{"settings":{"aliceSeed":"snake abandon tube border alone super velvet nuclear reward genuine gravity hungry","bobSeed":"law grid donkey label dilemma bacon chair gown economy agent sentence assault","lastBackup":1527488296800,"version":"0.0.4"}}`

**Comment by BobWallets** [comment]
Copying and pasting that backup into Restore is working for me using the latest v0.0.5 version. Can you verify?

It would be nice to add a drag-and-drop feature so you don't have to copy and paste the file backups.

**Comment by john-light** [comment]
Still getting this error with v0.0.5

`JSON.parse: unexpected character at line 1 column 1 of the JSON data`

**Comment by BobWallets** [comment]
Which device/browser are you using?

I just pasted it into Restore and then downloaded a new backup. Try copy/pasting this:

`{"settings":{"version":"0.0.4","routeTab":"Settings","simpleMode":true,"aliceSeed":"snake abandon tube border alone super velvet nuclear reward genuine gravity hungry","bobSeed":"law grid donkey label dilemma bacon chair gown economy agent sentence assault","bobIndex":0,"aliceIndex":0,"changeIndex":1,"disableAutoChange":false,"serverAddress":"https://api.bobwallet.fun","wholeNumbers":true,"ticker":"tBTC","lastBackup":1528229311100,"successfulRounds":0,"failedRounds":0,"publicBalance":0,"privateBalance":0,"totalFees":0},"completedRounds":[],"addressBalances":{"moiUQZoJN78SQ8rroL1YVw4oWHyFNPRtmT":42500000}}`

**Comment by john-light** [comment]
Was using 0.0.5 on Tor Browser in Linux Mint. Your backup did not work in that version (it was telling me I needed to be connected to Tor even though I already was) but it worked in the new 0.1.0 release. Closing for now, however might be worth noting somewhere the lack of backwards compatibility. (not super important since testnet; your call)
